
export type Language = 'fr' | 'en' | 'es' | 'zh';

export const translations = {
  fr: {
    home: "Accueil",
    live: "En Direct",
    upcoming: "À Venir",
    results: "Résultats",
    casino: "Casino",
    history: "Mes Paris",
    coupons: "Mes Coupons", // Added
    referral: "Parrainage",
    settings: "Paramètres",
    support: "Aide & Support",
    about: "À Propos & Serveurs",
    balance: "Solde",
    deposit: "Dépôt",
    withdraw: "Retrait",
    logout: "Déconnexion",
    search: "Rechercher...",
    coupon: "Coupon",
    placeBet: "Valider le Pari",
    potentialWin: "Gains Possibles",
    stake: "Mise",
    won: "Gagné",
    lost: "Perdu",
    pending: "En cours",
    share: "Partager",
    print: "Imprimer",
    download: "Télécharger",
    betDetails: "Détails du Pari",
    events: "Événements",
    status: "Statut",
    language: "Langue",
    notifications: "Notifications",
    theme: "Thème",
    darkMode: "Mode Sombre",
    lightMode: "Mode Clair",
    save: "Enregistrer",
    aiAnalysis: "Analyse IA",
    transactions: "Transactions",
    welcome: "Bienvenue",
    auto: "Auto",
    manual: "Manuel",
    autoCashout: "Encaissement Auto",
    cashout: "Encaisser",
    ageWarning: "Je certifie avoir plus de 21 ans et j'accepte les conditions.",
    ageError: "Vous devez avoir plus de 21 ans pour jouer.",
    searchTeam: "Rechercher une équipe ou un fan...",
    uploadFile: "Joindre un fichier",
    typeMessage: "Votre message...",
    voiceCall: "Appel Vocal",
    videoCall: "Appel Vidéo",
    calling: "Appel en cours...",
    incomingCall: "Appel Entrant",
    endCall: "Raccrocher",
    biometricSuccess: "Empreinte reconnue. Accès autorisé.",
    biometricFail: "Empreinte non reconnue. Accès refusé.",
    accessDenied: "ACCÈS REFUSÉ",
    downloadSuccess: "Ticket téléchargé avec succès !",
    shareError: "Le partage n'est pas supporté sur cet appareil.",
    serverConnected: "Serveur DB Connecté",
    syncing: "Synchronisation...",
    videoSource: "Source Vidéo",
    server1: "Serveur Principal",
    server2: "Serveur Secours",
    server3: "Flux Satellite",
    videoError: "Erreur flux. Changement de source...",
    terms: "Termes & Conditions",
    howToPlay: "Comment Jouer",
    paymentMethod: "Moyen de Paiement",
    selectMethod: "Choisir une méthode",
    connectPayPal: "Connecter PayPal",
    processing: "Traitement en cours...",
    partners: "Nos Partenaires Officiels",
    cardNumber: "Numéro de Carte",
    cardHolder: "Titulaire de la carte",
    expiry: "Expiration (MM/AA)",
    cvv: "CVV",
    cryptoNetwork: "Réseau / Crypto",
    walletAddress: "Adresse du Portefeuille",
    copyAddress: "Copier l'adresse",
    scanQr: "Scanner pour payer",
    minDeposit: "Dépôt Min.",
    minWithdraw: "Retrait Min.",
    // Payment Restrictions
    unavailableTitle: "Service Indisponible",
    useMomoForCard: "Pour payer par Carte (Visa/MC), veuillez utiliser l'option 'Mobile Money'. L'interface sécurisée acceptera votre carte.",
    methodUnavailable: "Ce moyen de paiement (PayPal/Crypto) n'est pas encore disponible. Veuillez patienter.",
    onlyMomoAvailable: "Seul Orange Money / Mobile Money est disponible pour le moment.",
    loadCoupon: "Charger ce Coupon",
    codeCopied: "Code copié !",
    noCoupons: "Aucun coupon enregistré."
  },
  en: {
    home: "Home",
    live: "Live",
    upcoming: "Upcoming",
    results: "Results",
    casino: "Casino",
    history: "My Bets",
    coupons: "My Coupons", // Added
    referral: "Referral",
    settings: "Settings",
    support: "Support",
    about: "About & Servers",
    balance: "Balance",
    deposit: "Deposit",
    withdraw: "Withdraw",
    logout: "Logout",
    search: "Search...",
    coupon: "Bet Slip",
    placeBet: "Place Bet",
    potentialWin: "Potential Win",
    stake: "Stake",
    won: "Won",
    lost: "Lost",
    pending: "Pending",
    share: "Share",
    print: "Print",
    download: "Download",
    betDetails: "Bet Details",
    events: "Events",
    status: "Status",
    language: "Language",
    notifications: "Notifications",
    theme: "Theme",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    save: "Save",
    aiAnalysis: "AI Analysis",
    transactions: "Transactions",
    welcome: "Welcome",
    auto: "Auto",
    manual: "Manual",
    autoCashout: "Auto Cashout",
    cashout: "Cash Out",
    ageWarning: "I certify I am over 21 and accept terms.",
    ageError: "You must be over 21 to play.",
    searchTeam: "Search team or fan...",
    uploadFile: "Upload File",
    typeMessage: "Type message...",
    voiceCall: "Voice Call",
    videoCall: "Video Call",
    calling: "Calling...",
    incomingCall: "Incoming Call",
    endCall: "End Call",
    biometricSuccess: "Fingerprint recognized. Access granted.",
    biometricFail: "Fingerprint not recognized. Access denied.",
    accessDenied: "ACCESS DENIED",
    downloadSuccess: "Ticket downloaded successfully!",
    shareError: "Sharing not supported on this device.",
    serverConnected: "DB Server Connected",
    syncing: "Syncing...",
    videoSource: "Video Source",
    server1: "Main Server",
    server2: "Backup Server",
    server3: "Satellite Feed",
    videoError: "Stream error. Switching source...",
    terms: "Terms & Conditions",
    howToPlay: "How to Play",
    paymentMethod: "Payment Method",
    selectMethod: "Select a method",
    connectPayPal: "Connect PayPal",
    processing: "Processing...",
    partners: "Official Partners",
    cardNumber: "Card Number",
    cardHolder: "Card Holder",
    expiry: "Expiry (MM/YY)",
    cvv: "CVV",
    cryptoNetwork: "Network / Coin",
    walletAddress: "Wallet Address",
    copyAddress: "Copy Address",
    scanQr: "Scan to Pay",
    minDeposit: "Min. Deposit",
    minWithdraw: "Min. Withdraw",
    unavailableTitle: "Service Unavailable",
    useMomoForCard: "To pay by Card (Visa/MC), please use the 'Mobile Money' option. The secure gateway will accept your card.",
    methodUnavailable: "This payment method (PayPal/Crypto) is not available yet. Please wait.",
    onlyMomoAvailable: "Only Orange Money / Mobile Money is available for now.",
    loadCoupon: "Load Coupon",
    codeCopied: "Code copied!",
    noCoupons: "No saved coupons."
  },
  es: {
    home: "Inicio",
    live: "En Vivo",
    upcoming: "Próximos",
    results: "Resultados",
    casino: "Casino",
    history: "Mis Apuestas",
    coupons: "Mis Cupones", // Added
    referral: "Referidos",
    settings: "Ajustes",
    support: "Soporte",
    about: "Acerca de y Servidores",
    balance: "Saldo",
    deposit: "Depósito",
    withdraw: "Retirar",
    logout: "Cerrar Sesión",
    search: "Buscar...",
    coupon: "Boleto",
    placeBet: "Apostar",
    potentialWin: "Ganancia Potencial",
    stake: "Apuesta",
    won: "Ganado",
    lost: "Perdido",
    pending: "Pendiente",
    share: "Compartir",
    print: "Imprimir",
    download: "Descargar",
    betDetails: "Detalles de Apuesta",
    events: "Eventos",
    status: "Estado",
    language: "Idioma",
    notifications: "Notificaciones",
    theme: "Tema",
    darkMode: "Modo Oscuro",
    lightMode: "Modo Claro",
    save: "Guardar",
    aiAnalysis: "Análisis IA",
    transactions: "Transacciones",
    welcome: "Bienvenido",
    auto: "Auto",
    manual: "Manual",
    autoCashout: "Retiro Auto",
    cashout: "Retirar",
    ageWarning: "Certifico que tengo más de 21 años.",
    ageError: "Debes tener más de 21 años para jugar.",
    searchTeam: "Buscar equipo o fan...",
    uploadFile: "Subir archivo",
    typeMessage: "Escribe un mensaje...",
    voiceCall: "Llamada de Voz",
    videoCall: "Videollamada",
    calling: "Llamando...",
    incomingCall: "Llamada Entrante",
    endCall: "Colgar",
    biometricSuccess: "Huella reconocida. Acceso concedido.",
    biometricFail: "Huella no reconocida. Acceso denegado.",
    accessDenied: "ACCESO DENEGADO",
    downloadSuccess: "¡Ticket descargado con éxito!",
    shareError: "Compartir no soportado en este dispositivo.",
    serverConnected: "Servidor DB Conectado",
    syncing: "Sincronizando...",
    videoSource: "Fuente de Video",
    server1: "Servidor Principal",
    server2: "Servidor Respaldo",
    server3: "Señal Satelital",
    videoError: "Error de flujo. Cambiando fuente...",
    terms: "Términos y Condiciones",
    howToPlay: "Cómo Jugar",
    paymentMethod: "Método de Pago",
    selectMethod: "Seleccionar método",
    connectPayPal: "Conectar PayPal",
    processing: "Procesando...",
    partners: "Socios Oficiales",
    cardNumber: "Número de Tarjeta",
    cardHolder: "Titular",
    expiry: "Expiración",
    cvv: "CVV",
    cryptoNetwork: "Red / Cripto",
    walletAddress: "Dirección de Billetera",
    copyAddress: "Copiar Dirección",
    scanQr: "Escanear para Pagar",
    minDeposit: "Depósito Min.",
    minWithdraw: "Retiro Min.",
    unavailableTitle: "Servicio No Disponible",
    useMomoForCard: "Para pagar con Tarjeta, use la opción 'Mobile Money'.",
    methodUnavailable: "Este método (PayPal/Cripto) no está disponible aún.",
    onlyMomoAvailable: "Solo Orange Money / Mobile Money está disponible por ahora.",
    loadCoupon: "Cargar Cupón",
    codeCopied: "¡Código copiado!",
    noCoupons: "Sin cupones guardados."
  },
  zh: {
    home: "首页",
    live: "滚球",
    upcoming: "早盘",
    results: "赛果",
    casino: "娱乐场",
    history: "我的注单",
    coupons: "我的优惠券", // Added
    referral: "推荐",
    settings: "设置",
    support: "支持",
    about: "关于与服务器",
    balance: "余额",
    deposit: "存款",
    withdraw: "提款",
    logout: "退出",
    search: "搜索...",
    coupon: "注单",
    placeBet: "下注",
    potentialWin: "可赢金额",
    stake: "本金",
    won: "赢",
    lost: "输",
    pending: "进行中",
    share: "分享",
    print: "打印",
    download: "下载",
    betDetails: "注单详情",
    events: "赛事",
    status: "状态",
    language: "语言",
    notifications: "通知",
    theme: "主题",
    darkMode: "深色模式",
    lightMode: "浅色模式",
    save: "保存",
    aiAnalysis: "AI分析",
    transactions: "交易记录",
    welcome: "欢迎",
    auto: "自动",
    manual: "手动",
    autoCashout: "自动兑现",
    cashout: "兑现",
    ageWarning: "我证明我已年满 21 岁。",
    ageError: "您必须年满 21 岁才能玩。",
    searchTeam: "搜索团队或粉丝...",
    uploadFile: "上传文件",
    typeMessage: "输入消息...",
    voiceCall: "语音通话",
    videoCall: "视频通话",
    calling: "呼叫中...",
    incomingCall: "来电",
    endCall: "挂断",
    biometricSuccess: "指纹识别成功。允许访问。",
    biometricFail: "指纹无法识别。拒绝访问。",
    accessDenied: "拒绝访问",
    downloadSuccess: "票据下载成功！",
    shareError: "此设备不支持分享。",
    serverConnected: "DB服务器已连接",
    syncing: "同步中...",
    videoSource: "视频源",
    server1: "主服务器",
    server2: "备份服务器",
    server3: "卫星信号",
    videoError: "流错误。正在切换源...",
    terms: "条款和条件",
    howToPlay: "怎么玩",
    paymentMethod: "付款方式",
    selectMethod: "选择方法",
    connectPayPal: "连接 PayPal",
    processing: "处理中...",
    partners: "官方合作伙伴",
    cardNumber: "卡号",
    cardHolder: "持卡人",
    expiry: "有效期",
    cvv: "安全码",
    cryptoNetwork: "网络",
    walletAddress: "钱包地址",
    copyAddress: "复制地址",
    scanQr: "扫码支付",
    minDeposit: "最低存款",
    minWithdraw: "最低提款",
    unavailableTitle: "服务不可用",
    useMomoForCard: "如需使用银行卡支付，请选择“Mobile Money”选项。",
    methodUnavailable: "该付款方式（PayPal/Crypto）暂不可用。",
    onlyMomoAvailable: "目前仅支持 Orange Money / Mobile Money。",
    loadCoupon: "加载优惠券",
    codeCopied: "代码已复制！",
    noCoupons: "没有保存的优惠券。"
  }
};

let currentLang: Language = 'fr';

export const setAppLanguage = (lang: Language) => {
  currentLang = lang;
  localStorage.setItem('sportbet_lang', lang);
};

export const getAppLanguage = (): Language => {
  return (localStorage.getItem('sportbet_lang') as Language) || 'fr';
};

export const t = (key: keyof typeof translations['fr']): string => {
  return translations[currentLang][key] || translations['fr'][key];
};